version: "3"

networks:
  otel-demo:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - otel-demo

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    ports:
      - "3000:3000"
    networks:
      - otel-demo

  prometheus:
    image: 
    volumes:
      - prometheus.yaml:/etc/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus.yaml"
    networks:
      - otel-demo

  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
      - "COLLECTOR_OTLP_ENABLED=true"
      - "JAEGER_DISABLED=true"
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - otel-demo

  otelcollector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "55679:55679"
    volumes:
      - otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - "--config=/etc/otel-collector-config.yaml"
    networks:
      - otel-demo

  grpc-server-node:
    build: ./grpc-server-node
    networks:
      - otel-demo

  grpc-client-py1:
    build: ./grpc-client-py
    command:
      - ""
    networks:
      - otel-demo

  grpc-client-py2:
    build: ./grpc-client-py
    command:
      - ""
    networks:
      - otel-demo
  