version: "3"


services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
      - "COLLECTOR_OTLP_ENABLED=true"
      - "JAEGER_DISABLED=true"
    ports:
      - "16686:16686"
      - "14250:14250"

  otelcollector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - jaeger
      - prometheus
      - loki
    ports:
      - "1888:1888"
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "55679:55679"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - "--config=/etc/otel-collector-config.yaml"

  grpc-server-node:
    build:
      context: .
      dockerfile: grpc-server-node.Dockerfile
    depends_on:
      - otelcollector
    environment:
      - "SERVICE_NAME=grpc-client-py1"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317"
    ports:
      - "50051:50051"

  grpc-client-py1:
    build:
      context: .
      dockerfile: grpc-client-py.Dockerfile
    depends_on:
      - otelcollector
      - grpc-server-node
    environment:
      - "SERVICE_NAME=grpc-client-py1"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317"
    command:
      - "--sleep=3"

  grpc-client-py2:
    build:
      context: .
      dockerfile: grpc-client-py.Dockerfile
    depends_on:
      - otelcollector
      - grpc-server-node
    environment:
      - "SERVICE_NAME=grpc-client-py2"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317"
    command:
      - "--min=20"
      - "--max=50"
  