receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]