# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: random.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crandom.proto\x12\x15randomNumberGenerator\"\x16\n\x07RandNum\x12\x0b\n\x03num\x18\x01 \x01(\x05\"*\n\x06MinMax\x12\x0f\n\x07minimum\x18\x01 \x01(\x05\x12\x0f\n\x07maximum\x18\x02 \x01(\x05\x32W\n\nRandNumGen\x12I\n\x06getNum\x12\x1d.randomNumberGenerator.MinMax\x1a\x1e.randomNumberGenerator.RandNum\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'random_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANDNUM._serialized_start=39
  _RANDNUM._serialized_end=61
  _MINMAX._serialized_start=63
  _MINMAX._serialized_end=105
  _RANDNUMGEN._serialized_start=107
  _RANDNUMGEN._serialized_end=194
# @@protoc_insertion_point(module_scope)
